### ISSUE TITLE
Document non-public shortcuts

### ISSUE THREAD

**Issue by georgjaehnig** [trovu/trovu#176]
Users can define in their `config.yml` namespaces, and they can have custom URLs, e.g.

```yaml
namespaces:
- o
- de
- .de
- name: mysecretshortcuts
  url: https://user:pass@jaehnig.org/secret/shortcuts.yml
```
As Trovu only runs in the client, the local browser can fetch this, without the outside world knowing `mysecretshortcuts`.

Test and document this.
