### ISSUE TITLE
Add tests for shortcut URLs

### ISSUE THREAD

**Issue by georgjaehnig** [trovu/trovu#179]
Shortcut URLs shall be testable (whether they still yield correct results when used).

One way of doing this could be adding an `expected:` field to `examples`, e.g. the Google shortcut:
```yaml
g 1:
  url: https://www.google.com/search?hl={$language}&q={%query}&ie=utf-8
  title: Google.com
  tags:
  - google
  - web search
  examples:
  - arguments: berlin
    description: Google search for "berlin"
```
... could be extended to
```yaml
   ...
  examples:
  - arguments: berlin
    description: Google search for "berlin"
    expected: '<textarea.*value="berlin"'
```
So this field shall accept regular expressions, for which shall be searching within the whole HTML content.

If needed later, one could allow to make `expected:` more specific:
```yaml
   ...
  examples:
  - arguments: berlin
    description: Google search for "berlin"
    expected:
      title: berlin - Google search
```
The key `title:` could actually be generalized and interpreted as any selector:
```yaml
    expected:
      div.navbar: foobar
```
Tests shall be run by a simple `fetch()`, which should be already [available in Node.js](https://blog.logrocket.com/fetch-api-node-js/).
