### ISSUE TITLE
(Automatically) create 0-argument shortcuts from 1+ arg shortcuts

### ISSUE THREAD

**Issue by georgjaehnig** [trovu/trovu#197]
It is desirable to always have a 0-arg shortcut with the domain/homepage as `url`, if there is a corresponding 1- or more argument shortcut. That way, the homepage is easily accessible in case the 1-arg shortcut is not working or not delivering the usecase.

Also, the 0-arg shortcut would not disturb.

Two approaches are possible:

1. virtually creating these shortcuts in the background by the code of [trovu-web](https://github.com/trovu/trovu-web), with no data in this trovu-data repo
1. (semi-)automatic creation (e.g. by a script) and writing those shortcuts into this trovu-data repo.

I prefer the 2nd approach as it's less complex, involves less magic and allows later editing of these shortcuts.

**Comment by texttheater** [comment]
Good idea. Adding 0-argument versions has always been a rather tedious bookkeeping task when adding new shortcuts. Being able to rely on a 0-argument version that is automatically available would be really nice. I slightly prefer the first approach as it would make the data files more compact and thereby easier to edit. Also it avoids any lag that a script might introduce. “Editing” 0-argument shortcuts would still be possible by creating them explicitly, which should then override the default.

**Comment by georgjaehnig** [comment]
Thanks for your input! I just evaluated the "automagic" approach and became strongly against it.

For one , we would create unclear situations: Assume

- `foo 0` pointing to `bar.com` in `o`. 
- `foo 1` pointing to `baz.com/{%query}` in `de`. 

Given the user has set the namespaces `o,de`, what should happen when they type `foo`? The automagic creation would need to be aware not only of the existing shortcuts in the same namespace, but also for the user's current settings.

For two, we would get a lot of useless 0-arg shortcuts like `.de.dbt 0`, `.de.dbn 0`, etc. 

**But:** We can leverage the include feature to avoid a lot of bookkepping, see [this commit](https://github.com/trovu/trovu/commit/91798828e80569316eb153ded5326cab52ca49c8) I just made:

```yaml
db 0:
  url: https://www.bahn.de/
  title: Deutsche Bahn
  tags:
  - bahn
  - railway
  - travel
db 1:
  url: https://reiseauskunft.bahn.de/bin/bhftafel.exe/dn?input={%Bahnhof}&boardType=dep&time=actual&productsDefault=1111101&start=yes
  title: Deutsche Bahn, Verspätungen / aktuelle Abfahrt
  include:
    key: db 0
```
The `include` includes all attributes that are not set in the current shortcut, in this case it tags. But also `title` would work, in case we want it to be the same.

Therefore I think, we should keep the YAML files in`/data as the source of thruth, and only have tooling scripts to simplify editing them, like

* a script that finds shortcuts with the same tags and same keyword, and adding includes
* a script that looks for missing 0-arg shortcuts and adding them. It could also be applied regulary.
