### ISSUE TITLE
Add variable for currency

### ISSUE THREAD

**Issue by georgjaehnig** [trovu/trovu#23]
Besides `{$language}` and `{$country}`, there could be `{$currency}` – for instance to be used as default for currency converters.

**Comment by georgjaehnig** [comment]
Subsequently, the currency shortcuts could be removed, e.g.

```yaml
pln 2:
  url: http://finance.yahoo.com/currency-converter/#from=pln;to={%to code};amt={%amount}
  title: 'Convert Polish złoty (Yahoo) '
  tags:
  - finance
  - currency
  - yahoo
  examples:
    eur, 1: Convert 1 Polish złoty into Euros
```
