### ISSUE TITLE
Allow user shortcuts to be part of config

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#235]
For a mechanism to fetch from private repositories hosted somewhere, it will be much easier if all shortcuts and settings are only in **one** file.

**Comment by georgjaehnig** [comment]
This could be implemented based on the `config.yml`:
```yaml
# Documentation:
# https://trovu.net/docs/users/advanced/#custom-configuration
namespaces:
- o
- en
- .us
- name: .
  shortcuts:
    examplekeyword 0: http://www.example.com/
    examplekeyword 1: http://www.example.com/?q=<query>
    examplekeyword 2:
      url: http://www.example.com/?q=<query>&p=<puery>
      title: Custom shortcut
      description: My custom shortcut with the keyword examplekeyword and 2 arguments.
      tags:
      - example
# defaultKeyword: g 
language: en
country: us
```
