### ISSUE TITLE
Allow examples to be filtered by config

### ISSUE THREAD

**Issue by georgjaehnig** [trovu/trovu#248]
Some shortcut examples only work if a certain config is used, e.g.
```yaml
db 2:
  url: 'https://reiseauskunft.bahn.de/bin/query.exe/d?S=<Start: {type: city}>%21&Z=<Ziel: {type: city}>%21&timesel=depart&start=1'
  title: Deutsche Bahn Fahrplanauskunft
  examples:
  - arguments: b, hh
    description: Nächste Bahn-Verbindung von Berlin nach Hamburg, Eingabe über Autokennzeichen
```
These city abbreviations only work if `country=de`.

Thus, allow setting
```yaml
  examples:
  - arguments: b, hh
    description: Nächste Bahn-Verbindung von Berlin nach Hamburg, Eingabe über Autokennzeichen
    config:
      country: de
```
The example will then only be displayed if `country=de`.
