### ISSUE TITLE
Default keyword does not seem to work

### ISSUE THREAD

**Issue by texttheater** [trovu/trovu#27]
Steps to reproduce
---

1. Go to https://trovu.net/index.html#github=texttheater
2. Enter something like `asdf` into the search box and hit enter

Expected behavior
---

Redirect to Google search for `asdf`

Actual behavior
---

Error message: `Could not find a matching shortcut for this query.`

Additional info
---

The default keyword is activated in [my config.yml](https://github.com/texttheater/trovu-data-user/blob/master/config.yml).

**Comment by georgjaehnig** [comment]
I've checked and #worksforme. ;)

Sometimes, Github needs some seconds/minutes to update the [raw export of your config.yml](https://raw.githubusercontent.com/texttheater/trovu-data-user/master/config.yml). So maybe try now again. If there are problems, you may always check *Settings wheel -> Debug*.

I've also added a note there informing about Github's possible delay in *Debug*.

**Comment by texttheater** [comment]
The issue persists. Here is the debug output:

```
namespaces:
  - github: texttheater
    name: kevang
    url: >-
      https://raw.githubusercontent.com/texttheater/trovu-data-user/master/shortcuts/{%keyword}.{%argumentCount}.yml
  - name: .de
    url: >-
      https://raw.githubusercontent.com/trovu/trovu-data/master/shortcuts/.de/{%keyword}/{%argumentCount}.yml
  - name: de
    url: >-
      https://raw.githubusercontent.com/trovu/trovu-data/master/shortcuts/de/{%keyword}/{%argumentCount}.yml
  - name: o
    url: >-
      https://raw.githubusercontent.com/trovu/trovu-data/master/shortcuts/o/{%keyword}/{%argumentCount}.yml
default keyword: g
language: de
country: de
github: texttheater
query: asdf
status: not_found
```
