### ISSUE TITLE
Replace YAML with TOML?

### ISSUE THREAD

**Issue by texttheater** [trovu/trovu#290]
Subjectively, I find the YAML format to be a bit of a headscratcher and it makes editing shortcuts less intuitive than it could be. Perhaps it's worth considering replacing it with something better-behaved like TOML at some point.

**Comment by georgjaehnig** [comment]
I'm surprised to hear that someone doesn't view YAML as the most intuitive notation language (so far developed) :)

I've had a look at TOML – is this how it a shortcut would look like?

```toml
[dbm_2]
url = 'http://mobile.bahn.de/bin/mobil/query.exe/dox?S=<Start: {type: city}>%21&Z=<Ziel: {type: city}>%21&start=1'
title = 'Deutsche Bahn Fahrplanauskunft, mobile Version'

[[dbm_2.examples]]
arguments = ['berlin', 'hamburg']
description = 'Nächste Verbindung von Berlin nach Hamburg'

[dbm_2.include]
key = 'db 0'
```
