### ISSUE TITLE
Make default namespaces and config configurable

### ISSUE THREAD

**Issue by jessek** [trovu/trovu#398]
trovu should offer a method to configure shortcuts unrelated to a language or country which:

* Are available to any user of a local installation of the server
* Override any existing shortcuts in the global o.yml file

I run a private trovu instance. I’d like to keep my code up-to-date with the public instance, especially the o.yml planet shortcuts. I am running this private server, however, to offer shortcuts to internal resources. I don’t want to publish these shortcuts to the global repository. 

This appears to be related to https://github.com/trovu/trovu/issues/336. That enhancement should, in theory, offer the ability to use a local shortcuts.yml file, which I believe will do what I want.

<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #398</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @jessek</code> (replace <code>20</code> with the amount, and <code>@jessek</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by georgjaehnig** [comment]
Hi @jessek, thanks for suggesting this.

So what you can do with the current code:

- After the build, put a `config.yml` into `./dist/public/`, with [user shortcuts defined inside it](https://trovu.net/docs/users/advanced/#user-namespaces), e.g.

```yaml
namespaces:
    - o
    - en
    - .us
    - name: righthere
      shortcuts:
          examplekeyword 0:
              url: https://example.com/
language: en
country: us
```
- Call `http://127.0.0.1:8081/?#configUrl=http%3A%2F%2F127.0.0.1%3A8081%2Fconfig.yml`

It should work on any server where `Allow CORS` is enabled (to fetch `config.yml`).

Let me know if this works for you, otherwise we can think about an enhancement.

**Comment by georgjaehnig** [comment]
And if you want to keep the shortcuts in a separate file, it should also work with a separate `shortcuts.yml`, and inside the `config.yml`:
```yaml
namespaces:
    - ...
    - url: http://127.0.0.1:8081/shortcuts.yml
      name: mydomain
```

**Comment by jessek** [comment]
Thanks for the response! I tried the first option you suggested, and it does technically work, but it won't work in my situation. Not all of my users are based in the US or use English. I don't want to require them to use a different language in order to access our internal resources. It's also a little inconvenient to require the extra arguments in the search URL. 

Is there a way to ensure the global shortcuts are available for everybody using the server, regardless of their language and country?

**Comment by georgjaehnig** [comment]
I assume your users won't use any personal settings, neither via `configUrl=` not `github=`?

Because by the latter, this could be possible: They'd have their own forks of [trovu-data-user](https://github.com/trovu/trovu-data-user), and edit their `config.yml` to:
```yaml
namespaces:
- o
- de # or any other
- .at # or any other
- foo # your company's shortcuts, placed in your local ./data/shortcuts/foo.yml
- github: .
  name: my
# defaultKeyword: g 
language: de # or any other
country: .at # or any other
```
Then they'd open `https://localtrovu.net/?#github=johndoe`

But yes, calling only `https://localtrovu.net/` would not include shortcuts from `foo.yml`.

If that's still something you want to do, we'd need to make the [default namespaces](https://github.com/trovu/trovu/blob/master/src/js/modules/Env.js#L332) configurable:
```js
    if (typeof this.namespaces != "object") {
      this.namespaces = ["o", this.language, "." + this.country];
    }
````
Could be done by some `.trovu.config.yml` to be placed in the project root, or some other approach, like a custom code file that would be included if present and override the current `setDefaults()`.

This would be an important design decision as it should be of course backwards compatible in the future. Let me think a bit on it until tomorrow, also let me know how you'd ideally like to have it configurable.

**Comment by georgjaehnig** [comment]
OK, here's a design I came up with. I'd put a `trovu.config.default.yml` in the project root. It'd be based on the structure of `config.yml` from [trovu-data-user](https://github.com/trovu/trovu-data-user), and make use of placeholders known from the shortcuts:
```yaml
namespaces:
- o
- <$language>
- .<$country>
# defaultKeyword: g 
language: en
country: us
```
Users running their own instance could then put another `trovu.config.yml` next to it, overriding those values they want to override.

Since `trovu.config.yml` would not be part of the repo, there would be no issues to keep the code up to date with `git pull` etc.

Let me know what you think.
